language: python
env:
  global:
  - PROJECT_NAME=chromosight
  - GITHUB_REPO_NAME=koszullab/chromosight
matrix:
  include:
  - python: '3.6'
  - python: '3.7'
    dist: xenial
    sudo: true
os:
- linux
install:
- pip install -v -Ur requirements.txt
- pip install codecov nose2
- pip install -e .
script:
- nose2 --with-coverage -s tests/
after_success:
- codecov
deploy:
  on:
    branch: master
    tags: true
  provider: pypi
  skip_existing: true
  user: cmdoret
  password:
    secure: L/eMxiGbYpYJcPGHRonWVFmfVQr57rdT5GEB6LmcgS6XKpGAqohu1sL27S51hTZF2i5uYefbSzdOFzBBw2wAXHVxGF4yPmTAfrek3sz0uk1aOrAcXYAMoQPevC8IjHBGoXejRdRxGDAdouUrcvbGbYAGZbgGtL1pcTJKzEUfjuLKvA5vldNhr3ERfPvyXVbVq3YNHfalYyBGeIjUFvDth4tz7AXIYOBXLp3AniVftIOrzK7N+JJLlfAU1RnncIJ0Udnu50LI8i71eEUft8xhDLHrnNc+q0SBlAtJqGdKEvopA6Xt7WvPzCdwo/u0QKlnwqE5j5EFmyUE8zKafKX5YQ674YJUzOCKctlW3uU/Xq3ZFkLjVa10eY364XMc2QXPHMhY7wXRGavDw2vkwsw/1ecCXhX25EI8tbOMsT5sDRk4bZjgjhDDwYPKFftIHid3er2vFVFO+Qe30vrq5wLpnpt2Cq/u5vyLeiTtlMHc7tZZE3Uyq7+crIRM4ta1lcyZyEAFWoSG5+THYn46a80f2kgJPwHByeVhghlM+o8Eq5hSagJhMhbDrBtDilCSIvw8heJRIkyJqNNwxFsOK8AT+k4r4ej91DjN7OmJ+Cf8WD2T1BrFfthJIQLkXFYpi0K5/CjIcv6F3Ow/R/NXSwuuamu/WQFb1vImf41hSaX2n9A=
  distributions: sdist bdist_wheel
